### ISSUE TITLE
Using it with f3-cortex

### ISSUE THREAD

**Issue by marcus-at-localhost** [AnandPilania/f3-validator#2]
Hey, I try build upon you f3-cortex example, but I have a hard time making it work.

The main problem right now is that 

a) `str_contains()` doesn't exist, it's `contains()` in the Helper Trait
b) `contains()` is protected so I can't access this helper function.

Could you please provide a working model?

Thanks!

**Comment by AnandPilania** [comment]
Hello @marcus-at-localhorst, thanks for using `f3-validator`.

Please provide sample code for better understanding the problem... because I can't get/found any bugs/probs...

`contains` func is in `helper` trait , so if u want to use it in external class/file, than `use Helper` in that class/file & access via `$this->contains`.

You can also use Validator without F3/framework, just fork & remove/update all F3 helpers, like, `Base` or `Audit` & implement your own functionality.

For F3 sample, please check `https://github.com/AnandPilania/F3-Modular` project or modules used in that Modular project.

Or if you need framework independent example, than let me know.

**Comment by marcus-at-localhost** [comment]
I was referring to the sample code that used the non-existent `str_contains` function (I know that part of the code is not necessarily needed)

```
protected $validator;
 public function __construct() {
      parent::__construct();
      $saveHandler = function() {
	       foreach($this->getFieldConfiguration() as $field => $conf) {
        	    if(isset($conf['validate'])) {
            	    $rules[$field] = $conf['validate'];
            	    $data[$field] = $this->get($field);
            	    if(str_contains($conf['validate'], 'confirmed')) {
        	    	   $confirmation = $field.'_confirmation';
                	   $data[$field.'_confirmation'] = null !== $f3->get('POST.'.$confirmation)?$f3->get('POST.'.$confirmation):$f3->get('GET.'.$confirmation);
            	    }
        	    }
    	    }
    	    $this->validator = Validator::instance()->validate($data, $rules);
	        return $this->validator->passed();
	   };
   $this->beforesave($saveHandler);
}
```

I'll try `use Helper;` in my model and thanks for pointing me to the f3-modular project, much appreciated.

**Comment by AnandPilania** [comment]
@marcus-at-localhorst ohhhh my mistake... actually this code is posted from my personal dev project where `str_contains` is external function. 

Sample code is updated, now you can use that function with `Validator::instance()->str_contains`

OR

If you needs that function, than please put function code into file & `include` it into your `index` or `bootstrap` file.

Please check [https://github.com/AnandPilania/f3-validator/blob/master/example_controller_use.txt](url) for `Controller` example (RECOMMENDED WAY).

 Thanks
